spring:
  redis:
    database: 0 #Redis中默认为我们提供了16个数据库，之间数据不互通，这里是选择要操作哪个数据库
    port: 6379
    jedis:
      pool:
        max-wait: 1ms
    host: 8.130.69.246
    password: 123456
  main:
    allow-circular-references: true
  datasource:
    druid:
      username: root
      password: root
      url: jdbc:mysql://localhost:3306/reggie
      driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    #静态资源前缀
    static-path-pattern: /static/**
  #静态资源缓存
  thymeleaf:
    cache: false
mybatis-plus:
  configuration:
    #全局驼峰命名
    map-underscore-to-camel-case: true
    #开启log4j2
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      #全局主键生成策略
      id-type: assign_id
server:
  port: 8888
ruiji:
  basePath: D:\\testcommon\\
  msgEnable: false

